### ISSUE TITLE
Fitur sign up tidak bisa di buka

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-qepo#1]
Pada halaman login.php ada tombol "sign up" di bawah namun pada saat di tekan tidak bisa pindah ke halaman sign up
![bug 1](https://user-images.githubusercontent.com/53895082/66935176-d8224b00-f065-11e9-8cb3-e79c59273d50.png)

**Comment by RizaruKecoak** [comment]
Harus nya sudah bisa mas, Terimakasih :]
