### ISSUE TITLE
SIGN UP.html seharusnya sign up.php ya kak

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-qepo#11]
![image](https://user-images.githubusercontent.com/49645946/67173751-d8b23d00-f3e9-11e9-9f5a-1aaf7c4286e3.png)
![image](https://user-images.githubusercontent.com/49645946/67173758-e23ba500-f3e9-11e9-9892-ee6b900498ad.png)

**Comment by RizaruKecoak** [comment]
Sebenernya dah di issue #1 , udah nge link ke yang bener, makasi ya mas :]
