### ISSUE TITLE
halaman rahasia dapat diakses tanpa login

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-qepo#12]
tanpa login bisa akses halaman yang seharusnya harus di akses dengan login dahulu
![image](https://user-images.githubusercontent.com/49645946/67173820-2464e680-f3ea-11e9-8968-d172fbe74cab.png)

**Comment by RizaruKecoak** [comment]
sudahhh
