### ISSUE TITLE
Salah title

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-qepo#2]
Pada halaman sign up seharusnya tulisan title pada file sign up.php adalah "Sign up" namun yang di tampilkan adalah tulisan "Sign Page"
![bug3](https://user-images.githubusercontent.com/53895082/66935600-744c5200-f066-11e9-8c47-ce0db7b7cbc4.png)

**Comment by RizaruKecoak** [comment]
Sudah mas :] , Terimakasih
