### ISSUE TITLE
Tulisan sign in tidak terlihat

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-qepo#3]
Pada file sign up.php tulisan "sign in" yang ada di bawah tidak terlihat karena jarak dari tombol sign up terlalu jauh dengan tulisan "sign in". Sudah saya coba di 4 browser dan hasilnya sama semua.
![bug 2](https://user-images.githubusercontent.com/53895082/66935874-fb012f00-f066-11e9-86a3-d174224b7846.png)

**Comment by RizaruKecoak** [comment]
harusnya sudah bisa mas

**Comment by RizaruKecoak** [comment]
terimakasih
