### ISSUE TITLE
Link tidak bekerja

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-qepo#4]
Link pada page sign up.php untuk melakukan sign in tidak bisa menampilkan form untuk login
![bug 4](https://user-images.githubusercontent.com/53895082/66936010-34d23580-f067-11e9-81d7-21e1387973a5.png)

**Comment by RizaruKecoak** [comment]
done :] thanks
