### ISSUE TITLE
Tidak ada fiturnya

### ISSUE THREAD

**Issue by Senivri** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-qepo#5]
Hanya bisa membuka halaman index.html#header dan halaman login.php

![Screenshot 2019-10-17 15 37 56](https://user-images.githubusercontent.com/55181810/66992498-1fefb380-f0f4-11e9-80ca-dff858e0074d.png)
![Screenshot 2019-10-17 15 38 06](https://user-images.githubusercontent.com/55181810/66992500-1fefb380-f0f4-11e9-984c-341fa9143687.png)

**Comment by Rinnabel** [comment]
coming soon ya :v
